//THIS FILE IS GENERATED BY tabtool, DO NOT EDIT IT!
//GENERATE TIME [2018/3/22 17:29:25]
#include <iostream>

#include "td_actor.hpp"
game_data::td_actor the_td_actor;
template<> ::game_data::td_actor const& GET_TABLE<::game_data::td_actor>() {
	return the_td_actor;
}
#include "td_actorlvup.hpp"
game_data::td_actorlvup the_td_actorlvup;
template<> ::game_data::td_actorlvup const& GET_TABLE<::game_data::td_actorlvup>() {
	return the_td_actorlvup;
}
game_data::td_regroup_actorlvupmap the_td_regroup_actorlvupmap;
template<> ::game_data::td_regroup_actorlvupmap const& GET_TABLE<::game_data::td_regroup_actorlvupmap>() {
	return the_td_regroup_actorlvupmap;
}
#include "td_actorskilllvup.hpp"
game_data::td_actorskilllvup the_td_actorskilllvup;
template<> ::game_data::td_actorskilllvup const& GET_TABLE<::game_data::td_actorskilllvup>() {
	return the_td_actorskilllvup;
}
#include "td_actortalent.hpp"
game_data::td_actortalent the_td_actortalent;
template<> ::game_data::td_actortalent const& GET_TABLE<::game_data::td_actortalent>() {
	return the_td_actortalent;
}

namespace game_data {
bool load_all_data() {
	if(!the_td_actor.Load()) { std::cerr << "load td_actor failed !!!" << std::endl; return false; }
	if(!the_td_actorlvup.Load()) { std::cerr << "load td_actorlvup failed !!!" << std::endl; return false; }
	if(!the_td_regroup_actorlvupmap.Load()) { std::cerr << "load actorlvupmap failed !!!" << std::endl; return false; }
	if(!the_td_actorskilllvup.Load()) { std::cerr << "load td_actorskilllvup failed !!!" << std::endl; return false; }
	if(!the_td_actortalent.Load()) { std::cerr << "load td_actortalent failed !!!" << std::endl; return false; }
	//relate code
	{
		for(auto p1 = the_td_actor.RawMap().begin(); p1 != the_td_actor.RawMap().end(); ++p1) {
			auto& v1 = (td_actor_item&)p1->second;
			auto const& k1 = v1.actor_id;
			for(auto p2 = the_td_actorlvup.RawMap().begin(); p2 != the_td_actorlvup.RawMap().end(); ++p2) {
				auto const& v2 = p2->second;
				auto const& k2 = v2.actor_id;
				if(k1 == k2) {
					v1.__relate__td_actorlvup_items.push_back(&v2);
				}
			}
		}
		for(auto p1 = the_td_actor.RawMap().begin(); p1 != the_td_actor.RawMap().end(); ++p1) {
			auto& v1 = (td_actor_item&)p1->second;
			auto const& k1 = v1.actor_id;
			for(auto p2 = the_td_actorskilllvup.RawMap().begin(); p2 != the_td_actorskilllvup.RawMap().end(); ++p2) {
				auto const& v2 = p2->second;
				auto const& k2 = v2.actor_id;
				if(k1 == k2) {
					v1.__relate__td_actorskilllvup_items.push_back(&v2);
				}
			}
		}
		for(auto p1 = the_td_actor.RawMap().begin(); p1 != the_td_actor.RawMap().end(); ++p1) {
			auto& v1 = (td_actor_item&)p1->second;
			auto const& k1 = v1.talent_id;
			for(auto p2 = the_td_actortalent.RawMap().begin(); p2 != the_td_actortalent.RawMap().end(); ++p2) {
				auto const& v2 = p2->second;
				auto const& k2 = v2.talent_id;
				if(k1 == k2) {
					v1.__relate__td_actortalent_items.push_back(&v2);
				}
			}
		}
	}
	return true;
}
}
