//THIS FILE IS GENERATED BY tabtool, DO NOT EDIT IT!
//GENERATE TIME [2018/1/19 20:42:26]
#pragma once
#include "readtablefield.h"
#include "myconfig.h"

namespace game_data {

struct tbsIdCount : public ITableObject<tbsIdCount>
{
	int32_t id;
	int32_t count;

	virtual bool FromString(string s)
	{
		DataReader dr;
		vector<string> vs = dr.GetStringList(s,',');
		if (vs.size() != 2)
		{
			ErrorLog("tbsIdCount字段配置错误");
			return false;
		}
		id = dr.GetValue<int32_t>(vs[0]);
		count = dr.GetValue<int32_t>(vs[1]);
		return true;
	}
};


struct tbsKeyValue : public ITableObject<tbsKeyValue>
{
	int32_t key;
	int32_t value;

	virtual bool FromString(string s)
	{
		DataReader dr;
		vector<string> vs = dr.GetStringList(s,',');
		if (vs.size() != 2)
		{
			ErrorLog("tbsKeyValue字段配置错误");
			return false;
		}
		key = dr.GetValue<int32_t>(vs[0]);
		value = dr.GetValue<int32_t>(vs[1]);
		return true;
	}
};


struct tbsTest : public ITableObject<tbsTest>
{
	int32_t a;
	string b;
	float c;

	virtual bool FromString(string s)
	{
		DataReader dr;
		vector<string> vs = dr.GetStringList(s,',');
		if (vs.size() != 3)
		{
			ErrorLog("tbsTest字段配置错误");
			return false;
		}
		a = dr.GetValue<int32_t>(vs[0]);
		b = (vs[1]);
		c = dr.GetValue<float>(vs[2]);
		return true;
	}
};

}
