//THIS FILE IS GENERATED BY tabtool, DO NOT EDIT IT!
//GENERATE TIME [2018/3/22 17:29:25]
#pragma once
# include "readtablefield.h"
# include "tablestruct.h"

namespace game_data {

struct td_actorlvup_item {
  int32_t id;
  int32_t actor_id;
  int32_t level;
  int32_t level_up_exp;
};

class td_actorlvup : public IConfigTable<td_actorlvup_item>{
public:
virtual bool Load() {
	ReadTableFile reader;
	reader.Initialize();
	if (!reader.Init(GetTableFile().c_str()))
		return false;
	try {
		DataReader dr;
		int iRows = reader.GetRowCount();
		int iCols = reader.GetColCount();
		for (int i = 1; i < iRows; ++i) {
			td_actorlvup_item item;
			item.id = dr.GetValue<int32_t>(reader.GetValue(i, "id"));
			item.actor_id = dr.GetValue<int32_t>(reader.GetValue(i, "actor_id"));
			item.level = dr.GetValue<int32_t>(reader.GetValue(i, "level"));
			item.level_up_exp = dr.GetValue<int32_t>(reader.GetValue(i, "level_up_exp"));
			m_Items[item.id] = item;
		}
	} catch(std::exception& e) {
		std::cerr << e.what() << std::endl;
		return false;
	}
	return true;
}
string GetTableFile() {
	string f = WORK_DIR;
	f = f + "ActorLvUp.txt";
	return f;
}
};
}

//regroup
extern game_data::td_actorlvup the_td_actorlvup;
namespace game_data {
class td_regroup_actorlvupmap : public IConfigTable<std::vector<const td_actorlvup_item*>>{
public:
virtual bool Load() {
	const auto& base_table = the_td_actorlvup.RawMap();
		for(auto& it : base_table) {
			m_Items[it.second.actor_id].push_back(&it.second);
		}
		return true;
	}
};
}

