//THIS FILE IS GENERATED BY tabtool, DO NOT EDIT IT!
//GENERATE TIME [2018/3/22 17:29:25]
#pragma once
# include "readtablefield.h"
# include "tablestruct.h"

namespace game_data {

struct td_actorlvup_item;
struct td_actorskilllvup_item;
struct td_actortalent_item;
struct td_actor_item {
  int32_t actor_id;
  int32_t talent_id;
  int32_t price;
  string desc;
  int32_t cost_type;
  std::vector<const td_actorlvup_item*> __relate__td_actorlvup_items;
  std::vector<const td_actorskilllvup_item*> __relate__td_actorskilllvup_items;
  std::vector<const td_actortalent_item*> __relate__td_actortalent_items;
};

class td_actor : public IConfigTable<td_actor_item>{
public:
virtual bool Load() {
	ReadTableFile reader;
	reader.Initialize();
	if (!reader.Init(GetTableFile().c_str()))
		return false;
	try {
		DataReader dr;
		int iRows = reader.GetRowCount();
		int iCols = reader.GetColCount();
		for (int i = 1; i < iRows; ++i) {
			td_actor_item item;
			item.actor_id = dr.GetValue<int32_t>(reader.GetValue(i, "actor_id"));
			item.talent_id = dr.GetValue<int32_t>(reader.GetValue(i, "talent_id"));
			item.price = dr.GetValue<int32_t>(reader.GetValue(i, "price"));
			item.desc = (reader.GetValue(i, "desc"));
			item.cost_type = dr.GetValue<int32_t>(reader.GetValue(i, "cost_type"));
			m_Items[item.actor_id] = item;
		}
	} catch(std::exception& e) {
		std::cerr << e.what() << std::endl;
		return false;
	}
	return true;
}
string GetTableFile() {
	string f = WORK_DIR;
	f = f + "Actor.txt";
	return f;
}
};
}


