//THIS FILE IS GENERATED BY tabtool, DO NOT EDIT IT!
//GENERATE TIME [2018/1/19 20:42:26]
#pragma once
# include "readtablefield.h"
# include "tablestruct.h"

namespace game_data {

struct td_maps_item;
struct td_chapter_item {
  int32_t id;
  int32_t chapter_id;
  int32_t star_num;
  int32_t create_id;
  std::vector<const td_maps_item*> __relate__td_maps_items;
};

class td_chapter : public IConfigTable<td_chapter_item>{
public:
virtual bool Load() {
	ReadTableFile reader;
	reader.Initialize();

	if (!reader.Init(GetTableFile().c_str()))
		return false;

	try {
		DataReader dr;
		int iRows = reader.GetRowCount();
		int iCols = reader.GetColCount();
		for (int i = 1; i < iRows; ++i) {
			td_chapter_item item;
			item.id = dr.GetValue<int32_t>(reader.GetValue(i, "id"));
			item.chapter_id = dr.GetValue<int32_t>(reader.GetValue(i, "chapter_id"));
			item.star_num = dr.GetValue<int32_t>(reader.GetValue(i, "star_num"));
			item.create_id = dr.GetValue<int32_t>(reader.GetValue(i, "create_id"));
			m_Items[item.id] = item;
		}
	} catch(std::exception& e) {
		std::cerr << e.what() << std::endl;
		return false;
	}
	return true;
}

string GetTableFile() {
	string f = WORK_DIR;
	f = f + "Chapter.txt";
	return f;
}

};

}
