//THIS FILE IS GENERATED BY tabtool, DO NOT EDIT IT!
//GENERATE TIME [2018/1/19 20:42:26]
#pragma once
# include "readtablefield.h"
# include "tablestruct.h"

namespace game_data {

struct td_maps_item {
  int32_t map_id;
  int32_t chapter_id;
  string desc;
};

class td_maps : public IConfigTable<td_maps_item>{
public:
virtual bool Load() {
	ReadTableFile reader;
	reader.Initialize();

	if (!reader.Init(GetTableFile().c_str()))
		return false;

	try {
		DataReader dr;
		int iRows = reader.GetRowCount();
		int iCols = reader.GetColCount();
		for (int i = 1; i < iRows; ++i) {
			td_maps_item item;
			item.map_id = dr.GetValue<int32_t>(reader.GetValue(i, "map_id"));
			item.chapter_id = dr.GetValue<int32_t>(reader.GetValue(i, "chapter_id"));
			item.desc = (reader.GetValue(i, "desc"));
			m_Items[item.map_id] = item;
		}
	} catch(std::exception& e) {
		std::cerr << e.what() << std::endl;
		return false;
	}
	return true;
}

string GetTableFile() {
	string f = WORK_DIR;
	f = f + "Maps.txt";
	return f;
}

};

}
