//THIS FILE IS GENERATED BY tabtool, DO NOT EDIT IT!
//GENERATE TIME [2018/3/20 16:09:18]
#pragma once
# include "readtablefield.h"
# include "tablestruct.h"

namespace game_data {

struct td_uidata_item {
  int32_t ui_id;
  string prefab_name;
  vector<string> load_relevance_prefabs;
  int32_t ui_layer_type;
  int32_t is_need_mask;
  int32_t resource_bar_type;
  int32_t is_open_resource_bar_touch;
  int32_t is_need_back_button;
};

class td_uidata : public IConfigTable<td_uidata_item>{
public:
virtual bool Load() {
	ReadTableFile reader;
	reader.Initialize();

	if (!reader.Init(GetTableFile().c_str()))
		return false;

	try {
		DataReader dr;
		int iRows = reader.GetRowCount();
		int iCols = reader.GetColCount();
		for (int i = 1; i < iRows; ++i) {
			td_uidata_item item;
			item.ui_id = dr.GetValue<int32_t>(reader.GetValue(i, "ui_id"));
			item.prefab_name = (reader.GetValue(i, "prefab_name"));
			item.load_relevance_prefabs = dr.GetList<string>(reader.GetValue(i, "load_relevance_prefabs"));
			item.ui_layer_type = dr.GetValue<int32_t>(reader.GetValue(i, "ui_layer_type"));
			item.is_need_mask = dr.GetValue<int32_t>(reader.GetValue(i, "is_need_mask"));
			item.resource_bar_type = dr.GetValue<int32_t>(reader.GetValue(i, "resource_bar_type"));
			item.is_open_resource_bar_touch = dr.GetValue<int32_t>(reader.GetValue(i, "is_open_resource_bar_touch"));
			item.is_need_back_button = dr.GetValue<int32_t>(reader.GetValue(i, "is_need_back_button"));
			m_Items[item.ui_id] = item;
		}
	} catch(std::exception& e) {
		std::cerr << e.what() << std::endl;
		return false;
	}
	return true;
}

string GetTableFile() {
	string f = WORK_DIR;
	f = f + "UIData.txt";
	return f;
}

};

}
