//THIS FILE IS GENERATED BY tabtool, DO NOT EDIT IT!
//GENERATE TIME [2018/1/19 20:42:26]
namespace activity_type {
	enum activity_type {
		success = 0, //成功-通用
		failed = 1, //失败-通用
	};
}
namespace quality {
	enum quality {
		blue_one = 1, //蓝+1
		blue_two = 2, //蓝+2
		blue_three = 3, //蓝+3
		blue_four = 4, //蓝+4
		xxxx = 5, //传说
	};
}
namespace resource_type {
	enum resource_type {
		rt_gold = 1, //金币
		rt_diamond = 2, //钻石
		rt_stamina = 3, //体力
		rt_exp = 4, //经验
	};
}
namespace res_code {
	enum res_code {
		success = 0, //成功-通用
		failed = 1, //失败-通用
	};
}
namespace attack_type {
	enum attack_type {
		fly = 1, //飞行
		water = 2, //水中
		land = 4, //陆地
		stealth = 8, //隐身
	};
}
