//THIS FILE IS GENERATED BY tabtool, DO NOT EDIT IT!
//GENERATE TIME [2018/3/22 17:29:25]
namespace activity_type {
	public enum activity_type {
		success = 0, //成功-通用
		failed = 1, //失败-通用
	};
}
namespace quality {
	public enum quality {
		blue_one = 1, //蓝+1
		blue_two = 2, //蓝+2
		blue_three = 3, //蓝+3
		blue_four = 4, //蓝+4
		xxxx = 5, //传说
	};
}
namespace resource_bar_type {
	public enum resource_bar_type {
		Empty = 0, //空类型
	};
}
namespace resource_type {
	public enum resource_type {
		rt_gold = 1, //金币
		rt_diamond = 2, //钻石
		rt_stamina = 3, //体力
		rt_exp = 4, //经验
	};
}
namespace res_code {
	public enum res_code {
		success = 0, //成功-通用
		failed = 1, //失败-通用
	};
}
namespace ui_layer_type {
	public enum ui_layer_type {
		none = 0, //空类型
		panel_layer = 1, //面板层
		alert_layer = 2, //弹框层
	};
}
namespace attack_type {
	public enum attack_type {
		fly = 1, //飞行
		water = 2, //水中
		land = 4, //陆地
		stealth = 8, //隐身
	};
}
