//THIS FILE IS GENERATED BY tabtool, DO NOT EDIT IT!
//GENERATE TIME [2018/1/19 20:42:26]

namespace game_data {
public class TableConfig : SingletonTable<TableConfig> {
	public bool LoadTableConfig() {
		if (!td_chapter.Instance.Load()) return false;
		if (!td_color.Instance.Load()) return false;
		if (!td_head.Instance.Load()) return false;
		if (!td_maps.Instance.Load()) return false;
		if (!td_test.Instance.Load()) return false;
        if (!td_chaptermap.Instance.Load()) return false;
	//relate code
		foreach(var p1 in td_head.Instance.GetTable()) {
			var v1 = p1.Value;
			var k1 = v1.head_id;
			foreach(var p2 in td_color.Instance.GetTable()) {
				var v2 = p2.Value;
				var k2 = v2.color_id;
				if(k1 == k2) {
					v1.__relate__td_color_items.Add(v2);
				}
			}
		}

        foreach (var p1 in td_chaptermap.Instance.GetTable()) {
            var v1 = p1.Value;
            var k1 = v1.chapter_id;
            foreach (var p2 in td_chapter.Instance.GetTable()) {
                var v2 = p2.Value;
                var k2 = v2.chapter_id;
                if (k1 == k2) {
                    v1.__regroup__td_chapter_items.Add(v2);
                }
            }
        }
            return true;
	}
}
}
