//THIS FILE IS GENERATED BY tabtool, DO NOT EDIT IT!
//GENERATE TIME [2018/3/22 17:29:25]

namespace game_data {
public class TableConfig : SingletonTable<TableConfig> {
	public bool LoadTableConfig() {
		if (!td_actor.Instance.Load()) return false;
		if (!td_actorlvup.Instance.Load()) return false;
		if (!td_regroup_actorlvupmap.Instance.Load()) return false;
		if (!td_actorskilllvup.Instance.Load()) return false;
		if (!td_actortalent.Instance.Load()) return false;
	//relate code
		foreach(var p1 in td_actor.Instance.GetTable()) {
			var v1 = p1.Value;
			var k1 = v1.actor_id;
			foreach(var p2 in td_actorlvup.Instance.GetTable()) {
				var v2 = p2.Value;
				var k2 = v2.actor_id;
				if(k1 == k2) {
					v1.__relate__td_actorlvup_items.Add(v2);
				}
			}
		}
		foreach(var p1 in td_actor.Instance.GetTable()) {
			var v1 = p1.Value;
			var k1 = v1.actor_id;
			foreach(var p2 in td_actorskilllvup.Instance.GetTable()) {
				var v2 = p2.Value;
				var k2 = v2.actor_id;
				if(k1 == k2) {
					v1.__relate__td_actorskilllvup_items.Add(v2);
				}
			}
		}
		foreach(var p1 in td_actor.Instance.GetTable()) {
			var v1 = p1.Value;
			var k1 = v1.talent_id;
			foreach(var p2 in td_actortalent.Instance.GetTable()) {
				var v2 = p2.Value;
				var k2 = v2.talent_id;
				if(k1 == k2) {
					v1.__relate__td_actortalent_items.Add(v2);
				}
			}
		}
			return true;
	}
}
}
