//THIS FILE IS GENERATED BY tabtool, DO NOT EDIT IT!
//GENERATE TIME [2018/3/22 17:29:25]

using System.Collections;
using System.Collections.Generic;
using System.Data;

namespace game_data {
public class td_actorlvup_item {
	public int id;
	public int actor_id;
	public int level;
	public int level_up_exp;
};

public class td_actorlvup : TableManager<td_actorlvup_item, td_actorlvup> {
	public override bool Load() {
		TableReader tr = new TableReader();
		DataReader dr = new DataReader();
		DataTable dt = tr.ReadFile(MyConfig.WorkDir+"ActorLvUp.txt");
		foreach(DataRow row in dt.Rows) {
			var item = new td_actorlvup_item();
			item.id = dr.GetValue<int>(row["id"].ToString());
			item.actor_id = dr.GetValue<int>(row["actor_id"].ToString());
			item.level = dr.GetValue<int>(row["level"].ToString());
			item.level_up_exp = dr.GetValue<int>(row["level_up_exp"].ToString());
			m_Items[item.id] = item;
		}
		return true;
	}
}
public class td_regroup_actorlvupmap : TableManager<List<td_actorlvup_item>, td_regroup_actorlvupmap> {
	public override bool Load() {
		var base_table = td_actorlvup.Instance.GetTable();
		foreach(var item in base_table) {
			if(!m_Items.ContainsKey(item.Value.actor_id)) {
				List<td_actorlvup_item> list = new List<td_actorlvup_item>();
				m_Items.Add(item.Value.actor_id, list);
			}
			m_Items[item.Value.actor_id].Add(item.Value);
		}
		return true;
	}
}
}

