//THIS FILE IS GENERATED BY tabtool, DO NOT EDIT IT!
//GENERATE TIME [2018/3/22 17:29:25]

using System.Collections;
using System.Collections.Generic;
using System.Data;

namespace game_data {
public class td_actorskilllvup_item {
	public int id;
	public int actor_id;
	public int skill_level;
	public int damage;
};

public class td_actorskilllvup : TableManager<td_actorskilllvup_item, td_actorskilllvup> {
	public override bool Load() {
		TableReader tr = new TableReader();
		DataReader dr = new DataReader();
		DataTable dt = tr.ReadFile(MyConfig.WorkDir+"ActorSkillLvUp.txt");
		foreach(DataRow row in dt.Rows) {
			var item = new td_actorskilllvup_item();
			item.id = dr.GetValue<int>(row["id"].ToString());
			item.actor_id = dr.GetValue<int>(row["actor_id"].ToString());
			item.skill_level = dr.GetValue<int>(row["skill_level"].ToString());
			item.damage = dr.GetValue<int>(row["damage"].ToString());
			m_Items[item.id] = item;
		}
		return true;
	}
}
}

