//THIS FILE IS GENERATED BY tabtool, DO NOT EDIT IT!
//GENERATE TIME [2018/3/22 17:29:25]

using System.Collections;
using System.Collections.Generic;
using System.Data;

namespace game_data {
public class td_actor_item {
	public int actor_id;
	public int talent_id;
	public int price;
	public string desc;
	public int cost_type;
	public List<td_actorlvup_item> __relate__td_actorlvup_items = new List<td_actorlvup_item>();
	public List<td_actorskilllvup_item> __relate__td_actorskilllvup_items = new List<td_actorskilllvup_item>();
	public List<td_actortalent_item> __relate__td_actortalent_items = new List<td_actortalent_item>();
};

public class td_actor : TableManager<td_actor_item, td_actor> {
	public override bool Load() {
		TableReader tr = new TableReader();
		DataReader dr = new DataReader();
		DataTable dt = tr.ReadFile(MyConfig.WorkDir+"Actor.txt");
		foreach(DataRow row in dt.Rows) {
			var item = new td_actor_item();
			item.actor_id = dr.GetValue<int>(row["actor_id"].ToString());
			item.talent_id = dr.GetValue<int>(row["talent_id"].ToString());
			item.price = dr.GetValue<int>(row["price"].ToString());
			item.desc = (row["desc"].ToString());
			item.cost_type = dr.GetValue<int>(row["cost_type"].ToString());
			m_Items[item.actor_id] = item;
		}
		return true;
	}
}
}

