//THIS FILE IS GENERATED BY tabtool, DO NOT EDIT IT!
//GENERATE TIME [2018/1/19 20:42:26]

using System.Collections;
using System.Collections.Generic;
using System.Data;

namespace game_data {
public class td_chapter_item {
	public int id;
	public int chapter_id;
	public int star_num;
	public int create_id;
};

public class td_chapter : TableManager<td_chapter_item, td_chapter> {
	public override bool Load() {
		TableReader tr = new TableReader();
		DataReader dr = new DataReader();
		DataTable dt = tr.ReadFile(MyConfig.WorkDir+"Chapter.txt");
		foreach(DataRow row in dt.Rows) {
			var item = new td_chapter_item();
			item.id = dr.GetValue<int>(row["id"].ToString());
			item.chapter_id = dr.GetValue<int>(row["chapter_id"].ToString());
			item.star_num = dr.GetValue<int>(row["star_num"].ToString());
			item.create_id = dr.GetValue<int>(row["create_id"].ToString());
			m_Items[item.id] = item;
		}
		return true;
	}
};

public class td_chaptermap_item {
   public int chapter_id;
   public List<td_chapter_item> __regroup__td_chapter_items = new List<td_chapter_item>();
};

public class td_chaptermap : TableManager<td_chaptermap_item, td_chaptermap> {
    public override bool Load() {
        TableReader tr = new TableReader();
        DataReader dr = new DataReader();
        DataTable dt = tr.ReadFile(MyConfig.WorkDir + "Chapter.txt");
        foreach (DataRow row in dt.Rows) {
            var item = new td_chaptermap_item();
            item.chapter_id = dr.GetValue<int>(row["chapter_id"].ToString());
            m_Items[item.chapter_id] = item;
        }
        return true;
    }
};

}

