//THIS FILE IS GENERATED BY tabtool, DO NOT EDIT IT!
//GENERATE TIME [2018/1/19 20:42:26]

using System.Collections;
using System.Collections.Generic;
using System.Data;

namespace game_data {
public class td_head_item {
	public int head_id;
	public int chapter_id;
	public int test_type;
	public List<td_color_item> __relate__td_color_items = new List<td_color_item>();
};

public class td_head : TableManager<td_head_item, td_head> {
	public override bool Load() {
		TableReader tr = new TableReader();
		DataReader dr = new DataReader();
		DataTable dt = tr.ReadFile(MyConfig.WorkDir+"Head.txt");
		foreach(DataRow row in dt.Rows) {
			var item = new td_head_item();
			item.head_id = dr.GetValue<int>(row["head_id"].ToString());
			item.chapter_id = dr.GetValue<int>(row["chapter_id"].ToString());
			item.test_type = dr.GetValue<int>(row["test_type"].ToString());
			m_Items[item.head_id] = item;
		}
		return true;
	}
}
}

