//THIS FILE IS GENERATED BY tabtool, DO NOT EDIT IT!
//GENERATE TIME [2018/1/19 20:42:26]

using System.Collections;
using System.Collections.Generic;
using System.Data;

namespace game_data {
public class td_maps_item {
	public int map_id;
	public int chapter_id;
	public string desc;
};

public class td_maps : TableManager<td_maps_item, td_maps> {
	public override bool Load() {
		TableReader tr = new TableReader();
		DataReader dr = new DataReader();
		DataTable dt = tr.ReadFile(MyConfig.WorkDir+"Maps.txt");
		foreach(DataRow row in dt.Rows) {
			var item = new td_maps_item();
			item.map_id = dr.GetValue<int>(row["map_id"].ToString());
			item.chapter_id = dr.GetValue<int>(row["chapter_id"].ToString());
			item.desc = (row["desc"].ToString());
			m_Items[item.map_id] = item;
		}
		return true;
	}
}
}

