//THIS FILE IS GENERATED BY tabtool, DO NOT EDIT IT!
//GENERATE TIME [2018/3/20 16:09:23]

using System.Collections;
using System.Collections.Generic;
using System.Data;

namespace game_data {
public class td_uidata_item {
	public int ui_id;
	public string prefab_name;
	public List<string> load_relevance_prefabs;
	public int ui_layer_type;
	public int is_need_mask;
	public int resource_bar_type;
	public int is_open_resource_bar_touch;
	public int is_need_back_button;
};

public class td_uidata : TableManager<td_uidata_item, td_uidata> {
	public override bool Load() {
		TableReader tr = new TableReader();
		DataReader dr = new DataReader();
		DataTable dt = tr.ReadFile(MyConfig.WorkDir+"UIData.txt");
		foreach(DataRow row in dt.Rows) {
			var item = new td_uidata_item();
			item.ui_id = dr.GetValue<int>(row["ui_id"].ToString());
			item.prefab_name = (row["prefab_name"].ToString());
			item.load_relevance_prefabs = dr.GetList<string>("load_relevance_prefabs");
			item.ui_layer_type = dr.GetValue<int>(row["ui_layer_type"].ToString());
			item.is_need_mask = dr.GetValue<int>(row["is_need_mask"].ToString());
			item.resource_bar_type = dr.GetValue<int>(row["resource_bar_type"].ToString());
			item.is_open_resource_bar_touch = dr.GetValue<int>(row["is_open_resource_bar_touch"].ToString());
			item.is_need_back_button = dr.GetValue<int>(row["is_need_back_button"].ToString());
			m_Items[item.ui_id] = item;
		}
		return true;
	}
}
}

